package com.springboot.jdbc;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class SpringBootJDBCController 
{
	private static String tableName="STUDENT";
	
	@Autowired  
    JdbcTemplate jdbc; 
	
	@RequestMapping("/")  
    public String welcomeNote() throws IOException
    {  
        String welcomeNote="Welcome...!!! Please do any CRUD operation in URL(create,insert,read,drop)";
		return welcomeNote;  
    } 
    @RequestMapping("/create")  
    public String create() throws IOException
    {          
    	String create = "CREATE TABLE "+ tableName +" (ID Integer)";
    	//String create = "CREATE TABLE "+ tableName +" (ID Integer, Name Varchar(32))";
    	//String create = "CREATE TABLE "+ tableName +" (ID INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), Name Varchar(32))";
    	jdbc.execute(create);
        return tableName+" Table Created Successfull!!!";  
    } 
    @RequestMapping("/insert")  
    public String insert()
    {  
    	for(int i=0; i<2; i++)
        { 
    	  String randomStr=String.valueOf((int) (Math.random() * 32767));
    	  String insert = "INSERT INTO " + tableName + " VALUES ("+randomStr+")";
          jdbc.execute(insert);
        }
        return"Data Inserted Successfull!!!";  
    } 
    @RequestMapping("/read")  
    public String read()
    {  
    	String read = "SELECT * FROM "+tableName;
    	List<Map<String, Object>> readList = jdbc.queryForList(read);
    	System.out.println("Data From "+tableName.toUpperCase());
        for (Map<String, Object> row : readList) 
        {
            System.out.println("ID : "+row.get("ID"));
        }
        return"Data Read Successfull!!!";  
    } 
    @RequestMapping("/drop")  
    public String drop() throws FileNotFoundException, IOException
    {  
    	String drop = "DROP TABLE "+tableName;
    	jdbc.execute(drop);   	
        return tableName+" Table Dropped Successfull!!!";  
    }
}
